[package]
name = "pacmanager-iced"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["image"]}
iced_aw = {version = "0.12.2", features = ["spinner", "badge"]}
rust-fuzzy-search = "0.1.1"
